/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chess.gui.component;

import java.awt.Color;
import java.awt.Component;
import java.awt.Graphics;
import java.awt.Rectangle;
import java.util.function.Predicate;
import javax.swing.JComponent;

/**
 *
 * @author yu-chi
 */
public class AbstractListPanel <T extends JComponent> extends javax.swing.JPanel {

    private final Class<T> contentType;
    JComponent last;
    private String emptyMessage = "";
    
    /**
     * Creates new form ListLayoutPanel
     */
    public AbstractListPanel(Class<T> contentType) {
        this.contentType = contentType;
        initComponents();
        last = listScrollPane;
    }

    @Override
    public void setBackground(Color bg) {
        super.setBackground(bg); //To change body of generated methods, choose Tools | Templates.
        if (listPanel != null)
            listPanel.setBackground(bg);
    }
    
    protected T get(Predicate<T> match) {
        for (Component c : listPanel.getComponents()) {
            if (contentType.isInstance(c)) {
                T s = (T)c;
                if (match.test(s)) {
                    return s;
                }
            }
        }
        return null;
    }
    
    protected void put(T component, boolean autoscroll) {
        Component c = listPanel.add(component);
        listPanel.invalidate();
        listScrollPane.invalidate();
        listPanel.revalidate();
        listPanel.setAutoscrolls(true);
        if (autoscroll && (last.getVisibleRect().height > 0 || c.getHeight() >= listScrollPane.getHeight()))
            listPanel.scrollRectToVisible(new Rectangle(0,listPanel.getPreferredSize().height, 10, 10));
        last = (T)c;
        listPanel.invalidate();
        listPanel.revalidate();
        listPanel.repaint();
    }
    
    protected T pop(Predicate<T> match) {
        T target = get(match);
        if (target == null)
            return target;
        listPanel.remove(target);
        listPanel.invalidate();
        listPanel.revalidate();
        listPanel.repaint();
        return target;
    }
    
    public String getEmptyMessage() {
        return emptyMessage;
    }

    public void setEmptyMessage(String emptyMessage) {
        this.emptyMessage = emptyMessage;
    }

    @Override
    public void paint(Graphics g) {
        super.paint(g); //To change body of generated methods, choose Tools | Templates.
        if (listPanel.getComponents().length == 0) {
            int width = g.getFontMetrics().stringWidth(emptyMessage);
            Color textColor = /* if the color cannot get any darker, a brigher color is used */
                    listPanel.getBackground().darker();
            float[] hsb = new float[3];
            Color.RGBtoHSB(textColor.getRed(), textColor.getGreen(), textColor.getBlue(), hsb);
            if (hsb[2] < 0.4f)
                textColor = Color.WHITE.darker().darker();
            g.setColor(textColor);
            g.drawString(emptyMessage, (getWidth() - width) / 2, getHeight() / 2);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        listScrollPane = new javax.swing.JScrollPane();
        listPanel = new javax.swing.JPanel();

        listScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        listPanel.setLayout(new javax.swing.BoxLayout(listPanel, javax.swing.BoxLayout.Y_AXIS));
        listScrollPane.setViewportView(listPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(listScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(listScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel listPanel;
    private javax.swing.JScrollPane listScrollPane;
    // End of variables declaration//GEN-END:variables
}
