/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chess.gui.component;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author yu-chi
 */
public class ChatEntryField extends javax.swing.AbstractButton {

    /**
     * Creates new form ChatEntryField
     */
    public ChatEntryField() {
        initComponents();
    }
    
    public void setDisplayName(String name) {
        nameLabel.setText(name);
    }
    
    private void setMessage(String message) {
        messageTextField.setText(message);
    }
    
    private String getMessage() {
        return messageTextField.getText();
    }
    
    public final void send() {
        ActionEvent evt = new ActionEvent(this, ActionEvent.ACTION_PERFORMED, null);
        for (ActionListener l : this.getActionListeners())
            l.actionPerformed(evt);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        messagePanel = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        messageTextField = new javax.swing.JTextField();
        colonLabel = new javax.swing.JLabel();
        sendButton = new javax.swing.JButton();

        messagePanel.setBackground(javax.swing.UIManager.getDefaults().getColor("TextField.background"));
        messagePanel.setBorder(javax.swing.BorderFactory.createLineBorder(javax.swing.UIManager.getDefaults().getColor("windowBorder")));

        nameLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        nameLabel.setText("Name");

        messageTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        messageTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                messageTextFieldActionPerformed(evt);
            }
        });

        colonLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        colonLabel.setText(":");

        javax.swing.GroupLayout messagePanelLayout = new javax.swing.GroupLayout(messagePanel);
        messagePanel.setLayout(messagePanelLayout);
        messagePanelLayout.setHorizontalGroup(
            messagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(messagePanelLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(nameLabel)
                .addGap(1, 1, 1)
                .addComponent(colonLabel)
                .addGap(2, 2, 2)
                .addComponent(messageTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE))
        );
        messagePanelLayout.setVerticalGroup(
            messagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(messagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(messageTextField)
                .addComponent(nameLabel)
                .addComponent(colonLabel))
        );

        sendButton.setText("Send");
        sendButton.setFocusable(false);
        sendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(messagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(3, 3, 3)
                .addComponent(sendButton))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(messagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(sendButton, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void sendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendButtonActionPerformed
        send();
    }//GEN-LAST:event_sendButtonActionPerformed

    private void messageTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_messageTextFieldActionPerformed
        send();
    }//GEN-LAST:event_messageTextFieldActionPerformed

    @Override
    public void setText(String text) {
        setMessage(text);
    }

    @Override
    public String getText() {
        return getMessage();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel colonLabel;
    private javax.swing.JPanel messagePanel;
    private javax.swing.JTextField messageTextField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JButton sendButton;
    // End of variables declaration//GEN-END:variables
}
