/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chess.gui.component;

import chess.gui.GameProperties;

/**
 *
 * @author yu-chi
 */
public class ChessBoardLabel extends javax.swing.JPanel {

    /**
     * Creates new form ChessBoardLabel
     */
    private ChessBoardLabel(char label) {
        initComponents();
        this.label.setText(Character.toString(label));
        this.label.setForeground(GameProperties.themeText());
    }
    
    public static ChessBoardLabel row(int r) {
        return new ChessBoardLabel((char)('0' + r));
    }
    
    public static ChessBoardLabel column(int c) {
        return new ChessBoardLabel((char)('A' + c - 1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label = new javax.swing.JLabel();

        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(11, 11));

        label.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        label.setForeground(new java.awt.Color(255, 255, 255));
        label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label, javax.swing.GroupLayout.DEFAULT_SIZE, 11, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 11, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel label;
    // End of variables declaration//GEN-END:variables
}
