/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chess.gui.component;

/**
 *
 * @author yu-chi
 */
public abstract class GameSessionPanel extends javax.swing.JPanel {
    
    private int playerCount = 0;
    public static final int MAX_PLAYERS = 2;
    
    /**
     * Creates new form ChatMessagePanel
     */
    public GameSessionPanel(String name, int playerCount) {
        initComponents();
        nameLabel.setText(name);
        setPlayerCount(playerCount);
    }
    
    public final String getSessionName() {
        return nameLabel.getText();
    }
    
    public final int getPlayerCount() {
        return this.playerCount;
    }
    
    public final void setPlayerCount(int playerCount) {
        this.playerCount = playerCount;
        playerCountLabel.setText(String.format("%d / %d", this.playerCount, MAX_PLAYERS));
    }
    
    public final void join() {
        joinSession(getSessionName());
    }
    
    protected abstract void joinSession(String sessionName);

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameLabel = new javax.swing.JLabel();
        playerCountLabel = new javax.swing.JLabel();
        joinButton = new javax.swing.JButton();

        nameLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        nameLabel.setText("Name");

        playerCountLabel.setText("1 / 2");

        joinButton.setText("Join");
        joinButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                joinButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(playerCountLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(joinButton)
                .addGap(6, 6, 6))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(playerCountLabel)
                .addComponent(joinButton))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void joinButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_joinButtonActionPerformed
        join();
    }//GEN-LAST:event_joinButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton joinButton;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel playerCountLabel;
    // End of variables declaration//GEN-END:variables
}
