/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chess.gui.component;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.event.ActionEvent;
import java.awt.geom.Rectangle2D;
import javax.swing.AbstractButton;
import javax.swing.BorderFactory;
import javax.swing.border.Border;

/**
 *
 * @author yu-chi
 */
public class PopupFrame extends AbstractButton {

    /**
     * Creates new form PopupFrame
     */
    public PopupFrame() {
        initComponents();
        setVisible(false);
    }
    
    @Override
    public void setText(String text) {
        messageLabel.setText(text);
    }
    
    @Override
    public String getText() {
        return messageLabel.getText();
    }

    @Override
    public void setBackground(Color bg) {
        dialogPanel.setBackground(bg);
    }

    @Override
    public Color getBackground() {
        return dialogPanel.getBackground();
    }

    @Override
    public void setForeground(Color bg) {
        messageLabel.setForeground(bg);
    }

    @Override
    public Color getForeground() {
        return messageLabel.getForeground();
    }

    public Border getDialogBorder() {
        return dialogPanel.getBorder();
    }

    public void setDialogBorder(Border border) {
        dialogPanel.setBorder(border);
        super.setBorder(BorderFactory.createEmptyBorder());
    }
    
    public void setButtonBackground(Color bg) {
        okButton.setBackground(bg);
    }

    public Color getButtonBackground() {
        return okButton.getBackground();
    }
    
    public void setButtonForeground(Color bg) {
        okButton.setForeground(bg);
    }

    public Color getButtonForeground() {
        return okButton.getForeground();
    }
    
    public void setShown(boolean aFlag) {
        super.setVisible(aFlag); //To change body of generated methods, choose Tools | Templates.
    }
    
    public boolean isShown() {
        return super.isVisible(); //To change body of generated methods, choose Tools | Templates.
    }
    
    public void dismiss() {
        if (this.actionListener != null)
            actionListener.actionPerformed(new ActionEvent(this, ActionEvent.ACTION_PERFORMED, null));
        this.setVisible(false);
    }

    @Override
    public void paint(Graphics g) {
        g.setColor(new Color(0, 0, 0, 100));
        g.fillRect(0, 0, getWidth(), getHeight());
        paintChildren(g);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogPanel = new javax.swing.JPanel();
        messageLabel = new javax.swing.JLabel();
        okButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(142, 142, 142));
        setOpaque(false);

        dialogPanel.setPreferredSize(new java.awt.Dimension(200, 150));

        messageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        messageLabel.setText("MESSAGE");

        okButton.setText("OK");
        okButton.setFocusable(false);
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dialogPanelLayout = new javax.swing.GroupLayout(dialogPanel);
        dialogPanel.setLayout(dialogPanelLayout);
        dialogPanelLayout.setHorizontalGroup(
            dialogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogPanelLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
            .addComponent(messageLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dialogPanelLayout.setVerticalGroup(
            dialogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogPanelLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(messageLabel)
                .addGap(26, 26, 26)
                .addComponent(okButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(dialogPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(dialogPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        dismiss();
    }//GEN-LAST:event_okButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel dialogPanel;
    private javax.swing.JLabel messageLabel;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables
}
